version: "3.7"
services: 
  python-ml: 
  image: python-ml
  ports:
    - "5000"
  networks: 
    - backend
  deploy: 
    replicas: 1
  restart_policy:
    condition: on-failure
  
  node: 
    image: gql-node
    networks:
      - frontend
    ports: "3000"
    deploy:
     replicas: 2